before:
  hooks:
    # This hook will run `go mod tidy` before releasing.
    - go mod tidy

project_name: kblight-api

archives:
  - format: tar.gz

    # A list of additional files to include in the archive.
    files:
      - LICENSE*
      - README*

    # Use zip for Windows archives.
    format_overrides:
      - goos: windows
        format: zip

universal_binaries:
  - replace: false

kos:
  - main: ./main.go
    repository: 4lch4/kblight-api
    bare: true
    tags:
      - latest
      - '{{.Tag}}'

sboms:
  - artifacts: archive

report_sizes: true

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  use: git
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

announce:
  # Requires the DISCORD_WEBHOOK_ID & DISCORD_WEBHOOK_TOKEN environment variables to be set.
  discord:
    enabled: true
