#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "k-blight-api"
primary_region = "den"

[env]
  API_NAME = "k-blight-api-dev"
  API_PORT = "8080"
  API_PREFIX = "/api/v1"
  API_VERSION = "0.0.1"
  AXIOM_DATA_SET = "k-blight-api"
  AXIOM_ORG_ID = "4lch4-industries-mneq"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
