# fly.toml app configuration file generated for k-blight-api on 2023-07-22T23:29:19-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "k-blight-api"
primary_region = "den"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[env]
  API_NAME="k-blight-api"
  API_VERSION="0.0.1"
  API_PREFIX="/api/v1"
  API_PORT="8080"
  AXIOM_ORG_ID="4lch4-industries-mneq"
  AXIOM_DATA_SET="k-blight-api"
