name: Build and Publish Docker Image

on:
  push:
    branches:
      - 'main'
      - 'develop'
    tags-ignore:
      - 'v*'

env:
  RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
  DOCKER_IMAGE: 4lch4/k-blight-api

jobs:
  build-and-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    outputs:
      status: ${{ job.status }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.DOCKER_IMAGE }}
          tags: |
            latest
            ${{ github.sha }}
            ${{ github.ref }}
            ${{ github.repository }}:latest

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push to DockerHub
        id: build
        uses: docker/build-push-action@v4
        with:
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true

  notify:
    name: Send Status Notification
    needs: build-and-push
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Discord Notification
        uses: 'Ilshidur/action-discord@0.3.2'
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: '${{ github.actor }} (GitHub Actions)'
          DISCORD_EMBEDS: '[ { "title": "${{ github.repository }}", "description": "The [latest build](${{ env.RUN_URL }}) for **${{ github.repository }}** has completed with the following status: **${{ needs.build-and-push.outputs.status }}**", "fields": [ { "name": "Status", "value": "${{ needs.build-and-push.outputs.status }}", "short": true, "inline": true }, { "name": "Event", "value": "${{ github.event_name }}", "short": true, "inline": true }, { "name": "Branch", "value": "${{ github.ref }}", "short": true, "inline": true }, { "name": "Commit", "value": "[${{ github.sha }}](${{ env.RUN_URL }})", "short": true, "inline": true }, { "name": "Workflow", "value": "[${{ github.workflow }}](${{ env.RUN_URL }})", "short": true, "inline": true } ] } ] '
        with:
          args: "The [latest build](${{ env.RUN_URL }}) for **${{ github.repository }}** has completed with the following status: **${{ needs.build-and-push.outputs.status }}**"