name: Go Releaser

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    name: Build Codebase
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # This is needed if you use fields like TagBody, TagSubject or TagContents in templates.
      - name: Fetch tags
        run: git fetch --force --tags

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.20'

      - name: Basic Build
        run: go build

  release:
    name: Build & Release
    runs-on: ubuntu-latest
    # An if statement that makes sure this job only runs when a tag is pushed
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # This is needed if you use fields like TagBody, TagSubject or TagContents in templates.
      - name: Fetch tags
        run: git fetch --force --tags

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.20'

      - uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
